### ISSUE TITLE
my session-string is always banned.

### ISSUE THREAD

**Issue by MissPuTrick** [gagharutyunyan1993/SaveRestrictedContentBot#2]

**Comment by gagharutyunyan1993** [comment]
How do you generate session?

**Comment by gagharutyunyan1993** [comment]
I looked at your commits, I advise you not to push private data such as API_ID, API_HASH, SESSION on github.

**Comment by MissPuTrick** [comment]
> 

using the @SessionStringGeneratorZBot bot

**Comment by MissPuTrick** [comment]
> I looked at your commits, I advise you not to push private data such as API_ID, API_HASH, SESSION on github.

ok thanks sir

**Comment by gagharutyunyan1993** [comment]
Try to generate using [replit](https://replit.com/@dashezup/generate-pyrogram-session-string). Can you also tell me what service you are using for bot deploy?

**Comment by MissPuTrick** [comment]
> 

Ok i try replit. I using vps digital ocean

**Comment by gagharutyunyan1993** [comment]
Аs I understand, the problem has been solved?
