### ISSUE TITLE
~@DroneBots problem

### ISSUE THREAD

**Issue by kizxlove** [gagharutyunyan1993/SaveRestrictedContentBot#3]
I am trying to deploy the bot on Digitalocean, but even though I have entered the right Vars , it still connects to a bot called Dronebot.
Log as below.
[saverestrictedcontentbot] [2023-04-22 20:36:52] starting Bot ~@DroneBots
[saverestrictedcontentbot] [2023-04-22 20:37:00] Userbot Error ! Have you added SESSION while deploying??

**Comment by gagharutyunyan1993** [comment]
I'm sorry, but I didn't try to deploy to DigitalОcean, so I didn't mention it in the documentation, I'll try and update the documentation when I have time.
