### ISSUE TITLE
Error saving private channel media

### ISSUE THREAD

**Issue by abdullayevich** [gagharutyunyan1993/SaveRestrictedContentBot#5]
Error : Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")

**Comment by gagharutyunyan1993** [comment]
Hello! I have updated the repositories. Please try doing a `git pull` and then try again.

**Comment by abdullayevich** [comment]
I will try. Thank you very much.

чт, 24 авг. 2023 г., 23:27 Gagik Harutyunyan ***@***.***>:
